
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/team01-f25-15
owner: ucsb-cs156-f25
repo_name: team01-f25-15
pull_requests: [{"author":{"id":"MDQ6VXNlcjc1NTA5OTg0","is_bot":false,"login":"AkulS1008","name":"Akul Singh"},"headRefName":"Akul-UCSBDiningMenuItems","number":43,"title":"Group Task #1","url":"https://github.com/ucsb-cs156-f25/team01-f25-15/pull/43"}]
