
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/team01-f25-15
owner: ucsb-cs156-f25
repo_name: team01-f25-15
pull_requests: [{"author":{"id":"U_kgDOCL5eCw","is_bot":false,"login":"timmywin","name":"tim"},"headRefName":"xy-RecommendationRequest-create-db","number":56,"title":"Xy recommendation request create db","url":"https://github.com/ucsb-cs156-f25/team01-f25-15/pull/56"},{"author":{"id":"U_kgDOB1PefA","is_bot":false,"login":"guntashgill","name":""},"headRefName":"GG-UCSBOrganization-delete-endpoint","number":55,"title":"Gg ucsb organization delete endpoint","url":"https://github.com/ucsb-cs156-f25/team01-f25-15/pull/55"},{"author":{"id":"U_kgDOB1PefA","is_bot":false,"login":"guntashgill","name":""},"headRefName":"GG-UCSBOrganization-put-endpoint","number":53,"title":"Gg ucsb organization put endpoint","url":"https://github.com/ucsb-cs156-f25/team01-f25-15/pull/53"},{"author":{"id":"MDQ6VXNlcjc1NTA5OTg0","is_bot":false,"login":"AkulS1008","name":"Akul Singh"},"headRefName":"Akul-UCSBDiningMenuItems","number":52,"title":"Added `GET` and `POST` methods for UCSB Dining Menu Items","url":"https://github.com/ucsb-cs156-f25/team01-f25-15/pull/52"},{"author":{"id":"U_kgDOB1PefA","is_bot":false,"login":"guntashgill","name":""},"headRefName":"GG-UCSBOrganization-get-endpoint","number":51,"title":"gg- ucsborganization added get endpoint","url":"https://github.com/ucsb-cs156-f25/team01-f25-15/pull/51"},{"author":{"id":"U_kgDOBpYh_w","is_bot":false,"login":"Shibainuinuinu","name":"Kelvin Fang"},"headRefName":"Kelvin-delete-for-helprequest-table","number":49,"title":"Kelvin delete for helprequest table - added DELETE endpoint to help request","url":"https://github.com/ucsb-cs156-f25/team01-f25-15/pull/49"}]
